version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    restart: always
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zoo1
    links:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: kafka1:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181
      KAFKA_CREATE_TOPICS: "logs:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  zoo1:
    image: elevy/zookeeper:latest
    environment:
      MYID: 1
      SERVERS: zoo1
    ports:
      - "2181:2181"
  tomcat1:
    image: jeanblanchard/tomcat:8.0.24-java8
    ports:
      - "8080:8080"
    volumes:
      - "./deploy:/opt/apache-tomcat-8.0.24/webapps/"
      - "./esb_root:/root/esb_root"
  
  elasticsearchkafkaconnector:
    image: elasticsearchkafkaconnector
    links:
      - elasticsearch
      - kafka1 
    restart: on-failure
  
  soapuimock:
    image: soapui
    ports:
      - "8091:8091"
  local_mongodb:
    extends:
      file: common.yml
      service: mongodb
    volumes:
      - ./local_datamongo2:/data/db
      - ./logs/mongodb:/var/log/mongodb

  local_gateway:
    extends:
      file: common.yml
      service: gateway
    links:
      - "local_mongodb:demo-mongodb"
    ports:
      - "8000:8082"
    volumes:
      - ./logs/gateway:/etc/gravitee.io/log
    environment:
      - GRAVITEEIO_MONGODB_HOST=demo-mongodb
      - GRAVITEEIO_ELASTIC_HOST=elasticsearch

  local_managementui:
    extends:
      file: common.yml
      service: managementui
    ports:
      - "8002:80"
    volumes:
      - ./logs/management-ui:/var/log/httpd
    environment:
      - MGMT_API_URL=http:\/\/localhost:8005\/management\/

  local_managementapi:
    extends:
      file: common.yml
      service: managementapi
    ports:
      - "8005:8083"
    volumes:
      - ./logs/management-api:/home/gravitee/logs
    links:
      - "local_mongodb:demo-mongodb"
    environment:
      - GRAVITEEIO_MONGODB_HOST=demo-mongodb
      - GRAVITEEIO_ELASTIC_HOST=elasticsearch
