FROM openjdk
COPY confluent-4.0.0/ ./confluent-4.0.0/
CMD ["confluent-4.0.0/bin/connect-standalone","confluent-4.0.0/bin/connect-standalone.properties","confluent-4.0.0/bin/elasticsearch-connect.properties"]
